let groupOfCompanies=[
    
    {name:"Meghna Group of Industries", rank:"1"},
    {name:"Square Group", rank:"2"},
    {name:"Pran-RFL Group", rank:"3"},
    {name:"Navan Group", rank:"4"},
    {name:"Abul Khair Group", rank:"5"},
    {name:"Bashundhara Group", rank:"6"},
    {name:"Ananda Group", rank:"7"},
    {name:"Rangs Group", rank:"8"},
    {name:"Aftab Group", rank:"9"},
    {name:"Kollo Group of Companies", rank:"10"},
    {name:"Runner Group of Companies", rank:"11"},
    {name:"Bengal Group of Companies", rank:"12"},
    {name:"Anwar Group of Companies", rank:"13"},
    {name:"Akij Group", rank:"14"},
    {name:"Aman Group", rank:"15"},
    {name:"A.K Khan Group", rank:"16"},
    {name:"aamra", rank:"17"},
    {name:"AAYAT Group Of Companies", rank:"18"},
    {name:"Alif Group", rank:"19"},
    {name:"Multimode Group", rank:"20"},
    {name:"Bio Group", rank:"21"},
    {name:"ORION Group", rank:"22"},
    {name:"WALTON Group", rank:"23"},
    {name:"Ifad Group", rank:"24"},
    {name:"ACI Group", rank:"25"},
    {name:"Corony Group", rank:"26"},
    {name:"Mondol Group", rank:"27"},
    {name:"Panam Group", rank:"28"},
    {name:"Palmal Group", rank:"29"},
    {name:"Fakir Group", rank:"30"},
    {name:"City Group", rank:"31"},
    {name:"Concord Group", rank:"32"},
    {name:"Jamuna Group", rank:"33"},
    {name:"Hamim Group", rank:"34"},
    {name:"Summit Group", rank:"35"},
    {name:"Transcom Group", rank:"36"},
    {name:"T K Group Of Industries", rank:"37"},
    {name:"Zaman Group Of Industries", rank:"38"},
    {name:"PHP Group BD", rank:"39"},
    {name:"Globe janakantha Shilpa Paribar", rank:"40"},
    {name:"Grameen Group", rank:"41"},
    {name:"Habib Group", rank:"42"},
    {name:"M.M Ispahani Group", rank:"43"},
    {name:"AL-Haramain Group", rank:"44"},
    {name:"Daffodil Group", rank:"45"},
    {name:"Gazi Group", rank:"46"},
    {name:"Knit Concern Group", rank:"47"},
    {name:"Panam Group", rank:"48"},
    {name:"Palmal Group", rank:"49"},
    {name:"Pacific Group", rank:"50"},

]

export{groupOfCompanies};